// Generated by CoffeeScript 2.7.0
var Modules;

import * as configmodule from "./configmodule.js";

import * as validatabletimestampmodule from "./validatabletimestampmodule.js";

Modules = {configmodule, validatabletimestampmodule};

export default Modules;
