// Generated by CoffeeScript 2.5.1
(function() {
  var fetch, network;

  network = {};

  //###########################################################
  fetch = require("node-fetch").default;

  //###########################################################
  network.postData = async function(url, data) {
    var options, response;
    options = {
      method: 'POST',
      credentials: 'omit',
      body: JSON.stringify(data),
      headers: {
        'Content-Type': 'application/json'
      }
    };
    response = (await fetch(url, options));
    if (response.status === 403) {
      throw new Error("Unauthorized!");
    }
    return response.json();
  };

  network.getData = async function(url) {
    var response;
    response = (await fetch(url));
    if (response.status === 403) {
      throw new Error("Unauthorized!");
    }
    return response.json();
  };

  module.exports = network;

}).call(this);
