// Generated by CoffeeScript 2.6.1
//###########################################################
export var postData = async function(url, data) {
  var options, response;
  options = {
    method: 'POST',
    credentials: 'omit',
    body: JSON.stringify(data),
    headers: {
      'Content-Type': 'application/json'
    }
  };
  response = (await fetch(url, options));
  if (response.status === 403) {
    throw new Error("Unauthorized!");
  }
  return response.json();
};

//###########################################################
export var getData = async function(url) {
  var response;
  response = (await fetch(url));
  if (response.status === 403) {
    throw new Error("Unauthorized!");
  }
  return response.json();
};
