// Generated by CoffeeScript 2.5.1
(function() {
  // thingybyteutils = {}

  // if typeof window = "object"
  //     thingybyteutils = require("secret-manager-crypto-utils")
  // else
  //     thingybyteutils = require("secret-manager-crypto-utils")

  // module.exports = thingybyteutils
  module.exports = require("secret-manager-crypto-utils");

}).call(this);
