// Generated by CoffeeScript 2.5.1
(function() {
  // thingybyteutils = {}

  // if typeof window == "object"
  //     thingybyteutils = require("thingy-byte-utils")
  // else
  //     thingybyteutils = require("thingy-byte-utils")

  // module.exports = thingybyteutils
  module.exports = require("thingy-byte-utils");

}).call(this);
